name: alcohol
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - numpy
  - python=3.11.5
  - pytorch::pytorch
  - scipy
  - seaborn
  - statsmodels
  - torchaudio
  - torchvision
  - scikit-learn
  - matplotlib
  - pandas
  - imbalanced-learn
prefix: /home/jjk297/.conda/envs/alcohol
